# -*- coding: utf-8 -*-
"""Data analysis and handling missing values.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bDO4QJRmW9Fp3C5XOJP0bodFZ8RhT9UR
"""



"""Go through this notebook to practice more by yourself

https://nbviewer.org/github/raqueeb/mltraining/blob/master/Python/titanic-project-test.ipynb?fbclid=IwAR3v44o5ycToeSUaDGXFkvVp8AJ2-4FbIH7ScxBH_20coh5BW7BAAZonQG8
"""

from google.colab import drive
drive.mount('/content/drive/')

import pandas as pd

train = pd.read_csv('/content/drive/MyDrive/pds-course/lectures/lecture-10/titanic-train.csv')

train

"""survival = বেঁচে গিয়েছেন/মারা গিয়েছেন 1 = বেঁচে গিয়েছেন; 0 = মারা গিয়েছেন

pclass = টিকেটের ক্লাস বা শ্রেণী 1st = প্রথম; 2nd = দ্বিতীয়; 3rd = তৃতীয়

sex = মহিলা না পুরুষ

Age = বয়স বছরে, এখানে অনেক ডাটা মিসিং

sibsp = উনার ভাইবোন অথবা স্বামী/স্ত্রীর সংখ্যা, ওই টাইটানিক জাহাজে, siblings / spouses সংখ্যায়

parch = উনার বাবা মা অথবা বাচ্চাদের সংখ্যা, parent /children সংখ্যায়

ticket = টিকেট নাম্বার, কেবিন নম্বর ধরে টিকেট নম্বর

fare = টাইটানিক যাত্রীর ভাড়া

cabin = টাইটানিকের কেবিন নাম্বার

embarked = কোথা থেকে উঠেছেন, বিশেষ করে কোন পোর্ট থেকে C = Cherbourg, Q = Queenstown, S = Southampton
"""

train.shape

train.info()

train['Embarked'].unique()

train.notnull().sum()

"""আমরা দেখতে পাচ্ছি বয়স ভ্যারিয়েবলটাতে অনেক ভ্যালু মিসিং। বেশ সমস্যার কথা। ৮৯১ সারির মধ্যে ৭১৪ সারিতে ভ্যালু আছে। কেবিনে দেখা যাচ্ছে মাত্র ২০৪টাতে ভ্যালু আছে। ভয়ঙ্কর সমস্যা। ডাটাফ্রেমে কোন কোন ভ্যারিয়েবলে কতোটা ভ্যালু মিসিং (NaN) সেটা জানতে আমরা ব্যবহার করছি isnull() মেথড + এরপর সেগুলোকে যোগ করেছি sum() মেথড দিয়ে।"""

train['Title'] = train['Name'].str.extract(' ([A-Za-z]+)\.', expand=False)

train['Title'].value_counts()

"""টাইটেলগুলোকে ম্যাপ করি সংখ্যার সাথে
আগের মতো বাকি অদরকারি টাইটেলগুলোকে ম্যাপ করে দেই ৩ এর সাথে।

Mr : 0
Miss : 1
Mrs: 2
Others: 3
"""

# # mr, miss, mrs, - - -
# # if train['Title'] not one of mr, miss, mrs , set the Title ABC
valid_titles = ['mr', 'miss', 'mrs']

# # Update the 'Title' column: set to 'ABC' if it's not in valid_titles
train.loc[~train['Title'].isin(valid_titles), 'Title'] = 'others'

title_mapping = {"Mr": 0, "Miss": 1, "Mrs": 2,
                 "Master": 3, "Dr": 3, "Rev": 3, "Col": 3, "Major": 3, "Mlle": 3,"Countess": 3,
                 "Ms": 3, "Lady": 3, "Jonkheer": 3, "Don": 3, "Dona" : 3, "Mme": 3,"Capt": 3,"Sir": 3 }
train['Title'] = train['Title'].map(title_mapping)

train

"""প্রচুর বয়সের ডাটা মিসিং আছে আমাদের ডাটাসেটে
একটা কাজ করি বরং

টাইটেলের "গড়" বয়স দিয়ে ভরে ফেলি আমাদের না থাকা ভ্যালুগুলোর জায়গায়
"""

# Group by "Title" and get the count of each group
group_count = train.groupby("Title").size()

# Display the counts
print(group_count)

# fill missing age with median age for each title (Mr, Mrs, Miss, Others)

train["Age"] = train["Age"].fillna(train.groupby("Title")["Age"].transform("median"))

train.loc[train['Age'] <= 16, 'Age'] = 0
train.loc[(train['Age'] > 16) & (train['Age'] <= 26), 'Age'] = 1
train.loc[(train['Age'] > 26) & (train['Age'] <= 36), 'Age'] = 2
train.loc[(train['Age'] > 36) & (train['Age'] <= 62), 'Age'] = 3
train.loc[ train['Age'] > 62, 'Age'] = 4

train

train['Embarked'].value_counts()

train['Embarked'].isnull().sum()

# fill null values of Emabrked with 'S'
train['Embarked'] = train['Embarked'].fillna('S')

train['Embarked'].isnull().sum()

"""#  Task 1
 create a new column -> **Category** -> Basic, Economy, Premium based on Fare

 Fare 0 to 50 -> Basic

 Fare more than 50 to 100 -> Economy

 Fare more than 100 to infinity -> Premium

#  Task 2

Create a Map object like Basic : 0, Economy : 1, Premium : 2

Replace category with mapping 0, 1, 2
"""

train['Category'] = None

train.loc[(train['Fare'] >= 0) & (train['Fare'] <= 50), 'Category'] = 'Basic'
train.loc[(train['Fare'] > 50) & (train['Fare'] <= 100), 'Category'] = 'Economy'
train.loc[train['Fare'] > 100, 'Category'] = 'Premium'

train.head()

category_mapping = {"Basic": 0, "Economy": 1, "Premium": 2 }
train['Category'] = train['Category'].map(category_mapping)

