# -*- coding: utf-8 -*-
"""Pandas DataFrames Hierarchical Indexing (Multi Index).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HCU2oWjLKwN7FIMzybRajPFH8LNCHt3Y
"""

import pandas as pd

raw_data = {
    'department': ['CSE', 'CSE', 'SWE', 'SWE', 'EEE', 'EEE'],
    'rank': ['1st','2nd','1st','2nd','1st','2nd'],
    'name': ['Habib','Ashik','Kamal','Rakib','Rini','Mahi'],
    'marks1': [80,78,90,84,82,76],
    'marks2': [82,76,86,88,83,92]
}

df = pd.DataFrame(raw_data)

df

# add multi-indexing on (department, rank)
df1 = df.set_index(['department', 'rank'])
df1

"""Notice above dataframe table. Columns 'department' and 'rank are removed from the table, just showing as index. But if we want to keep them, we should create index as following"""

df2 = df.set_index(['department', 'rank'], drop = False)
df2

"""Lets Select some data/rows from multi - indexed dataframe"""

studentsOfCSE = df2.loc['CSE']
studentsOfCSE

firstOfCSE = df2.loc['CSE','1st']
firstOfCSE

df2.index

